### ISSUE TITLE
Better README documentation

### ISSUE THREAD

**Issue by Jzarecta** [hasgeek/lastuser#105]
Can we have better documentation that install instructions, I would like to see, how to call it, how to use it as a server and as a client (if it supports them) and if it's not supported please make it happen. 

I would love to see also alternative ways to achieve the sign on, server, and different setups in special cases. Out of the top of my head, I can think of sending the authentication credentials over an XHR instead of regular loading pages.

**Comment by sindhus** [comment]
The current README has instructions on installation. Is there a reason why this issue is still left open?

**Comment by jace** [comment]
We're no longer supporting third party usage of Lastuser as the app's development is centred almost entirely around HasGeek's needs.
