### ISSUE TITLE
Introduce roles alongside permissions

### ISSUE THREAD

**Issue by jace** [hasgeek/lastuser#118]
Permissions are assigned to users against apps. Roles, OTOH, are assigned to teams within organizations.

Roles potentially replace the hardcoded "Owners" role that exists at the database level.

**Comment by jace** [comment]
As discussed in #128 (context objects), app-level roles shouldn't be mixed up with Lastuser roles. We should drop that entirely from the scope of this ticket.

This leaves us with a fairly simple role definition:

```python
class ROLE(LabeledEnum):
    owner = (1, 'owner', __("Owner"))
    admin = (2, 'admin, __("Admin"))
    member = (3, 'member', __("Member"))
```

`role` is now a status column on the relationship that makes users part of a team or organization.

**Comment by jace** [comment]
Role definitions:

1. Users can have a role in an organization (per #151). Being an "owner" gives them full control of the organization. Being an "admin" gives them control over membership not including owners, and no access to organization settings such as the username and title. Being a "member" grants no privileges.

2. Users can have roles in teams. The same principles apply, but these roles do not extend to the organization.

3. Optional: Teams can have roles in organizations (same set of roles). This has potential complications and can confuse users, so we should consider not supporting this. For example, a user with "Member" role in a Team that in turn has "Owner" role on the Organization is now an owner even though they think they are a member: ownership of the organization trickles down into ownership of the team and a member of the team is now an owner of the team.

**Comment by rudimk** [comment]
Wow. This was one of the first things we tried to flesh out back in Nov 2014.

**Comment by jace** [comment]
If we remove the Members and Owners teams, this may break Flask-Lastuser, which expects userids against them, especially when syncing teams in the client app.

**Comment by jace** [comment]
![Telegram permissions](https://user-images.githubusercontent.com/26695/31498087-b283012a-af7e-11e7-9321-cf2e61e80c83.png)

Example from Telegram of permissions attached to a role. If we use this approach, apps can specify additional permissions to Lastuser, which it can include in the UI.

**Comment by jace** [comment]
> If we remove the Members and Owners teams, this may break Flask-Lastuser, which expects userids against them, especially when syncing teams in the client app.

As discussed in #232:

Temporary workaround: every organization has two uuid columns to represent owners and members, and the API passes these on in place of teams; all other teams will be deleted.

Roles will be limited to Admin or Member and specified as an admin flag on the org membership model. We'll eschew more elaborate role definition for now while we migrate organisations to Funnel as per #232.

**Comment by jace** [comment]
Following from #232, organizations and roles will move into Funnel via hasgeek/funnel#401. This ticket is no longer necessary. Lastuser's code will remain untouched, only marked as deprecated, until client apps have been reoriented to Funnel and the code can be removed.
