### ISSUE TITLE
Login beacons causing csrf_invalid error in some conditions

### ISSUE THREAD

**Issue by jace** [hasgeek/lastuser#122]
As a side-effect of implementing #52: In Chrome Android (and maybe in other browsers), opening a logged out client app page while logged in on the server causes the page to redirect to Lastuser for auth, but when Lastuser sends the browser back with an auth code, the client app does not recognise the CSRF "state" token and errors with csrf_invalid.

It's unclear why the state supplied by the client app was not set in a session cookie. Attempting to login manually at this point works fine.

**Comment by jace** [comment]
We are no longer able to reproduce this issue.

**Comment by jace** [comment]
@sindhus reports that Safari still has this problem.

**Comment by sindhus** [comment]
Yep, in Safari (8.0.6 (10600.6.3), I go to hasjob.co, after logging in through twitter I get to see https://auth.hasgeek.com and then when I go back to hasjob.co, i get redirected to https://auth.hasgeek.com/login …its a cycle! I dont ever get to browse hasjob board as a logged in use.

**Comment by jace** [comment]
Can you confirm this only happens in Safari?

**Comment by sindhus** [comment]
Yep only on Safari. Tested on Firefox (37.0.2), Chromium (Version 42.0.2311.135 (64-bit)), Chrome(Version 43.0.2357.124 (64-bit)) and Canary (Version 45.0.2431.0 canary (64-bit)) -- all good.

**Comment by jace** [comment]
Fixed in hasgeek/flask-lastuser@ae59a02fcb26c021e47349191faebc440261b268.
