### ISSUE TITLE
Wildcard access to client resources

### ISSUE THREAD

**Issue by jace** [hasgeek/lastuser#156]
A client can ask for `namespace:*` for another client, thereby getting an access token that behaves exactly like a user session cookie. This is meant for use by native app clients that replicate the functionality of a web app.

However, since `*` represents unlimited scope access, it should perhaps be a restricted resource, available only to client apps that share the same owner.

**Comment by miteshashar** [comment]
You could also flag every resource to indicate whether it should give itself up to wildcard tokens. Helps lastuser and clients protect sensitive resources.

**Comment by jace** [comment]
Wildcard was introduced specifically for native client apps. Not sure it's a good idea to have additional exclusions. Let's see when the use case comes up?

**Comment by miteshashar** [comment]
@jace Got it :)
