### ISSUE TITLE
Exception: Must provide secret_key to use csrf

### ISSUE THREAD

**Issue by divyenduz** [hasgeek/lastuser#163]
I am getting the following error on following the test setup instructions from README.md

<img width="874" alt="screen shot 2016-02-05 at 9 01 04 am" src="https://cloud.githubusercontent.com/assets/746482/12837908/1df9fa02-cbed-11e5-816f-0fae936d3c63.png">

Is this a bug or am I missing something silly ?

**Comment by jace** [comment]
Add `SECRET_KEY='random value here'` in your settings.

**Comment by divyenduz** [comment]
SECRET_KEY = 'random_secret_key' is present in my settings.py file

**Comment by divyenduz** [comment]
Ignore this, location of my settings.py was wrong. I had kept it outside the instance directory.

**Comment by jace** [comment]
👍🏼
