### ISSUE TITLE
Exception: Must provide secret_key to use csrf.

### ISSUE THREAD

**Issue by salus-sage** [hasgeek/lastuser#167]
Hi,
I followed the steps in setup from Readme, but unable to run the app. screen shot is from the error. 
I have the secret_key configured in the settings.py, but still unable to get it work, not sure what i'm missing.
![lastuser-error](https://cloud.githubusercontent.com/assets/6399323/12972373/ad67ff86-d0ca-11e5-8d43-08204b26e713.png)

**Comment by jace** [comment]
Dupe of #163. Is your `settings.py` in the `instance` folder?

**Comment by salus-sage** [comment]
Settings.py is in instance folder, but after running runserver.py, i got following warnings 
Did not find settings file settings.py for additional settings, skipping it
Did not find settings file development.py for additional settings, skipping it
/home/triptone/Projects/lastuser/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
/home/triptone/Projects/lastuser/local/lib/python2.7/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
None
