### ISSUE TITLE
Rename "organizations" to "groups"

### ISSUE THREAD

**Issue by jace** [hasgeek/lastuser#19]
The term "organization" confuses people into assuming that it's only meant for formal organizations. Renaming the concept to "group" will make this easier to accept.

**Comment by jace** [comment]
Corollary: having "teams" inside "groups" will confuse people even more. We need better vocabulary.

**Comment by iambibhas** [comment]
Do people Expect formal organizations where we're trying to push "groups"? Just wondering if we'll confuse people even more using "group" when they will be looking for "Organization"

**Comment by jace** [comment]
The dictionary definition of "organization" is "an organized group of people with a particular purpose, such as a business or government department". This definition says nothing about a formal definition such as being a registered entity, but it does imply that these people have definite relationships with each other.

On GitHub, it makes sense for the term to refer to people who intend to work together on shared code.

"Organization" is the right term to use anytime we're referring to a group that has a structure that exists outside Lastuser, when the database structure inside Lastuser is meant to reflect this existing external structure.

Unfortunately, in common parlance in India, "organization" does imply there's some formality to it. Our users will be more familiar with the vocabulary of WhatsApp than GitHub, and so will understand terms like "group" and "admin" better.
