### ISSUE TITLE
Users' handles should not be dictionary keywords

### ISSUE THREAD

**Issue by booleanbalaji** [hasgeek/lastuser#201]
Example: https://kilter.talkfunnel.com/2017/9-microbiome-gut-function-and-immunity

The handle used here is nutritionist and is misleading. Keywords like engineer, doctor, developer should not be allowed

**Comment by jace** [comment]
Are their examples of such policies in effect elsewhere?

**Comment by booleanbalaji** [comment]
Not publicly, but there are conversations on product forums on keywords which are not allowed. 

Google blocks usernames with keywords like accountant or gmail or chrome and some more sensitive stuff like dkennedy. It also seems like they ban the usage of celebrity names. Pfeiffer@gmail.com is not allowed, but a combination is, because of Michelle Pfeiffer.
Yahoo is a little more aggressive, not allowing even die.

Source:
https://productforums.google.com/forum/#!topic/gmail/eNKw3y5G_KY

**Comment by jace** [comment]
What about Twitter and GitHub? I'm more inclined towards their policies as they allow usernames to be changed, unlike Google and Yahoo where they are permanent.

**Comment by jace** [comment]
Closing this as we are retaining our liberal policy. Besides, this is not a technical issue to be dealt with in Lastuser.
