### ISSUE TITLE
User.add_x

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/lastuser#54]
https://github.com/hasgeek/lastuser/pull/53#discussion-diff-5863677

**Comment by sindhus** [comment]
@miteshashar I see your work in PR #53 has been merged. Is there a reason why #54 is still open?

**Comment by miteshashar** [comment]
@sindhus IIRC, there is a suggestion from @jace in the note in #53 linked by me in the first comment, which I have mentioned would need to be handled in a separate PR.
So, if `user.add_email` & `user.add_phone` may have been handled elsewhere, this issue can be closed.
But, I'd suggest you verify this well before closing the issue, since a lot of it is not fresh in my mind.

**Comment by jace** [comment]
Closing since both these methods have existed for a while now.
