### ISSUE TITLE
Add new login providers

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/lastuser#80]
- [ ] twitter w/posting permissions
- [ ] FB
- [x] LinkedIn
- [ ] bitbucket
- [ ] Meetup.com
- [ ] dribbble. TBC
- [ ] Behance. TBC
- [ ] Indeed. TBC. Ask for API access
- [ ] StackOverflow Careers. TBC. Validate use case.

**Comment by jace** [comment]
Closing this, as the only login provider of interest is Facebook. We can open a new ticket when it's actually required.
