### ISSUE TITLE
Trust Model

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/lastuser#94]
A `Trust` model that keeps a record of Trusted entities that a client has trusted access to.

Use cases:
- A client getting trusted access only to specified trusted resources. For e.g. If the specified resource is a trusted resource, https://github.com/hasgeek/lastuser/blob/master/lastuser_core/registry.py#L60 checks if the given client is a trusted client and hence gives access to it. Instead, it will check the `Trust` model to determine if the client has access to the given trusted resource.
- A client getting trusted access only to specified trusted services. For e.g. a particular service, will check the `Trust` model to determine if a given client should be allowed to use it.
- A client getting access to specified trusted login providers, like those which allow write operations or give a general API access to the login provider. For e.g. based on the `Trust` model, a login provider like `GitHubProvider` determines whether a given client should be allowed to use the login provider with certain scope or if the login provider's API access should be allowed to the client.

**Comment by jace** [comment]
Fixed with automatic scope in #166 and #169.
